### ISSUE TITLE
Terminado under Anaconda (with IPython 3.1) not creating terminal

### ISSUE THREAD

**Issue by rgbkrk** [takluyver/terminado#15]
Current traceback I'm seeing in the notebook server logs:

```
[I 20:00:59.744 NotebookApp] New terminal with automatic name: 1
[E 20:01:01.204 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.4/site-packages/tornado/http1connection.py", line 236, in _read_message
        delegate.finish()
      File "/opt/conda/lib/python3.4/site-packages/tornado/httpserver.py", line 269, in finish
        self.delegate.finish()
      File "/opt/conda/lib/python3.4/site-packages/tornado/web.py", line 1898, in finish
        self.execute()
      File "/opt/conda/lib/python3.4/site-packages/tornado/web.py", line 1918, in execute
        **self.handler_kwargs)
      File "/opt/conda/lib/python3.4/site-packages/tornado/websocket.py", line 127, in __init__
        **kwargs)
      File "/opt/conda/lib/python3.4/site-packages/tornado/web.py", line 176, in __init__
        self.clear()
      File "/opt/conda/lib/python3.4/site-packages/tornado/web.py", line 280, in clear
        self.set_default_headers()
      File "/opt/conda/lib/python3.4/site-packages/IPython/html/base/handlers.py", line 209, in set_default_headers
        self.set_header("Access-Control-Allow-Origin", self.allow_origin)
      File "/opt/conda/lib/python3.4/site-packages/tornado/websocket.py", line 375, in _disallow_for_websocket
        if self.stream is None:
    AttributeError: 'TermSocket' object has no attribute 'stream'
```

/cc @asmeurer

**Comment by takluyver** [comment]
IPython/Jupyter issue, see jupyter/jupyter_notebook#50 and ipython/ipython#8375
